$ErrorActionPreference='Stop';[Console]::OutputEncoding=[Text.Encoding]::UTF8
if($env:RELAY_REAL_TERMINAL-ne'1'){Write-Host 'SUITE SKIP relay-psmux-real (set RELAY_REAL_TERMINAL=1)';exit 0}
if(-not(Get-Command psmux -ErrorAction SilentlyContinue)){Write-Host 'SUITE FAIL relay-psmux-real (psmux missing)';exit 1}
$script:failed=0;$script:assertions=0
function Assert-True([bool]$c,[string]$n){$script:assertions++;if($c){Write-Host "PASS  $n"}else{Write-Host "FAIL  $n";$script:failed++}}
. (Join-Path $PSScriptRoot '../adapters/psmux-adapter.ps1')
$root=Join-Path ([IO.Path]::GetTempPath()) "relay-psmux-real-$([guid]::NewGuid().ToString('N'))";[void](New-Item -ItemType Directory -Path $root)
$sid="S-R$((Get-Random -Minimum 1000 -Maximum 9999))";$receipt=@{launch_id='L-0001';session_id=$sid};'{}'|Set-Content -LiteralPath (Join-Path $root 'L-0001.json') -Encoding utf8NoBOM
$run=@{run_id='RUN-REAL';paths=@{launches=$root}};$node=@{node_id='A';brief_ref='FAKE'}
$params=Import-PowerShellDataFile (Join-Path $PSScriptRoot '../contracts/relay-params.psd1');$adapter=New-RelayPsmuxAdapter @{HandleRoot=$root;Params=$params;LaunchCommand={param($r,$n,$run)@('pwsh','-NoProfile','-NoExit','-Command','Write-Host RELAY-REAL-BANNER; 1..15|ForEach-Object{Write-Host tick;Start-Sleep 1}; while(1){Start-Sleep 1}')}}
try{$launch=&$adapter.launch $receipt $node $run;Assert-True $launch.ok 'real launch succeeds';Assert-True (-not[string]::IsNullOrWhiteSpace($launch.handle.session_name)) 'session name present';Assert-True (-not[string]::IsNullOrWhiteSpace($launch.handle.psmux_session_id)) 'psmux id present';Assert-True (-not[string]::IsNullOrWhiteSpace($launch.handle.pane_id)) 'pane id present';Assert-True ($launch.handle.pane_pid-gt0) 'pane pid present';Assert-True (Test-Path (Join-Path $root "$sid.json")) 'registry exists';$exact=@(& psmux list-sessions -F '#{session_name}'|Where-Object{$_-ceq$launch.handle.session_name});Assert-True ($exact.Count-eq1) 'session exists exactly once';Assert-True (Find-RelayVisibleWindow $launch.handle.window_title) 'window is visible';$probe=&$adapter.probe $sid;Assert-True ($probe.terminal_state-eq'running') 'initial probe running';$idleSw=[Diagnostics.Stopwatch]::StartNew();do{Start-Sleep 1;$probe=&$adapter.probe $sid}while($probe.terminal_state-ne'idle'-and$idleSw.Elapsed.TotalSeconds-lt(15+$params.IdleAfterSeconds+15));Assert-True ($probe.terminal_state-eq'idle') 'later probe idle (silence beyond IdleAfterSeconds)';$stop=&$adapter.stop $sid;Assert-True ($stop.ok-and$stop.exited_after_ms-le($params.StopDeadlineSeconds*1000)) 'stop bounded';Assert-True ((&$adapter.probe $sid).terminal_state-eq'exited') 'probe sees exit';Assert-True (-not(Get-Process -Id $launch.handle.client_pid -ErrorAction SilentlyContinue)) 'client exits';Assert-True ((&$adapter.stop $sid).reason-eq'unknown-session') 'second stop is unknown'}finally{if($launch-and$launch.ok){& psmux kill-session -t $launch.handle.session_name 2>$null};Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}
Write-Host "ASSERTIONS $script:assertions";if($script:failed){Write-Host "SUITE FAIL ($script:failed)";exit 1};Write-Host 'SUITE PASS';exit 0
