$ErrorActionPreference='Stop';[Console]::OutputEncoding=[Text.Encoding]::UTF8
$script:failed=0;$script:assertions=0;$script:roots=[Collections.Generic.List[string]]::new();$script:t=[DateTimeOffset]::Parse('2026-08-15T09:00:00Z')
function Assert-True([bool]$c,[string]$n){$script:assertions++;if($c){Write-Host "PASS  $n"}else{Write-Host "FAIL  $n";$script:failed++}}
function RF([string]$p){Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot "fixtures/runner/$p")|ConvertFrom-Json -AsHashtable -DateKind String}
function New-Case([string]$adapter){$script:t=[DateTimeOffset]::Parse('2026-08-15T09:00:00Z');$root=Join-Path ([IO.Path]::GetTempPath()) "relay-test-failures-$([guid]::NewGuid().ToString('N'))";$script:roots.Add($root);$a=New-RelayFakeAdapter (RF "adapter/$adapter");$r=New-RelayRun $root 'RUN-FAKE-DHR02' $a {$script:t};[void](Submit-RelayProposal $r (RF 'plans/plan-v1-single-A.json') 0);$active=(Get-FileHash $r.paths.active_plan).Hash;$auth=(Get-FileHash $r.paths.authority).Hash;[void](Start-RelayNodeAttempt $r 'A');@{run=$r;adapter=$a;active=$active;auth=$auth}}
function Tick($x,[int]$n){1..$n|ForEach-Object{[void](Invoke-RelayTick $x.run);$script:t=$script:t.AddSeconds(60)}}
function Assert-Paused($x,[string]$label){$node=$x.run.state.nodes.A;Assert-True ($node.task_state -eq 'paused' -and $node.scheduling -eq 'paused') "$label paused invariant";Assert-True (@(Get-RelayReadyNodes $x.run).Count -eq 0) "$label no ready node";$before=@($x.adapter.calls|Where-Object verb -eq 'probe').Count;[void](Invoke-RelayTick $x.run);$after=@($x.adapter.calls|Where-Object verb -eq 'probe').Count;Assert-True ($before -eq $after) "$label no further probe";Assert-True ((Get-FileHash $x.run.paths.active_plan).Hash -eq $x.active -and (Get-FileHash $x.run.paths.authority).Hash -eq $x.auth) "$label authority bytes invariant"}
. (Join-Path $PSScriptRoot '../runner/relay-runner.ps1');. (Join-Path $PSScriptRoot '../adapters/fake-adapter.ps1')
try{
  $x=New-Case 'probe-never-running.json';Tick $x 3;Assert-True ($x.run.state.nodes.A.terminal_state -eq 'unknown' -and $x.run.state.nodes.A.pause_reason -eq 'launch-deadline-exceeded') 'launch deadline fail closes';Assert-True ((Read-RelayEvents $x.run|Where-Object{$_.kind-eq'launch_failed'}).reason -eq 'launch-deadline-exceeded') 'launch deadline event';Assert-Paused $x 'launch deadline'
  $x=New-Case 'probe-errors-3.json';Tick $x 4;$errs=@(Read-RelayEvents $x.run|Where-Object{$_.kind-eq'observation'-and$_.probe_error});Assert-True ($x.run.state.nodes.A.terminal_state -eq 'unknown' -and $x.run.state.nodes.A.result_status -eq 'interrupted_unknown') 'probe loss projects both dimensions';Assert-True ($x.run.state.nodes.A.pause_reason -eq 'probe-lost') 'probe loss reason';Assert-True ($errs.Count -eq 3 -and $errs[-1].consecutive_probe_failures -eq 3) 'three probe failures recorded';Assert-Paused $x 'probe loss'
  $x=New-Case 'probe-running-forever.json';Tick $x 31;Assert-True ($x.run.state.nodes.A.pause_reason -eq 'stalled' -and $x.run.state.nodes.A.terminal_state -eq 'unknown') 'stall threshold fail closes';Assert-True (@(Read-RelayEvents $x.run|Where-Object reason -eq 'stall-threshold-exceeded').Count -eq 1) 'stall event recorded';Assert-Paused $x 'stall'
  $x=New-Case 'probe-running-forever.json';1..40|ForEach-Object{[void](Invoke-RelayTick $x.run);if($_%10-eq 0){[void](Submit-RelayCheckpointFile $x.run 'A' (Join-Path $PSScriptRoot 'fixtures/runner/checkpoints/ckpt-A1-working.json'))};$script:t=$script:t.AddSeconds(60)};Assert-True ($x.run.state.nodes.A.task_state -eq 'active') 'periodic checkpoint prevents stall';Assert-True ($x.run.state.nodes.A.terminal_state -eq 'running') 'heartbeat remains running with progress'
  $x=New-Case 'probe-running-forever.json';Tick $x 1;[void](Submit-RelayCheckpointFile $x.run 'A' (Join-Path $PSScriptRoot 'fixtures/runner/checkpoints/ckpt-A1-decision.json'));Tick $x 40;Assert-True ($x.run.state.nodes.A.result_status -eq 'decision_required' -and $x.run.state.nodes.A.task_state -eq 'active' -and $x.run.state.nodes.A.pause_reason -eq '') 'decision wait forty ticks is not stalled'
  $x=New-Case 'probe-errors-3.json';Tick $x 1;[void](Submit-RelayCheckpointFile $x.run 'A' (Join-Path $PSScriptRoot 'fixtures/runner/checkpoints/ckpt-A1-decision.json'));Tick $x 3;Assert-True ($x.run.state.nodes.A.terminal_state -eq 'unknown' -and $x.run.state.nodes.A.result_status -eq 'interrupted_unknown' -and $x.run.state.nodes.A.pause_reason -eq 'probe-lost') 'decision wait still fail closes after three probe errors';Assert-Paused $x 'decision probe loss'
  $x=New-Case 'probe-exit-early.json';Tick $x 2;Assert-True ($x.run.state.nodes.A.result_status -eq 'interrupted_unknown' -and $x.run.state.nodes.A.pause_reason -eq 'exit-without-result') 'exit without result fail closes';Assert-Paused $x 'early exit'
  $x=New-Case 'host-exit.json';Tick $x 2;Assert-True ($x.run.state.nodes.A.result_status -eq 'interrupted_unknown' -and $x.run.state.nodes.A.pause_reason -eq 'exit-without-result') 'host exit uses fail closed observation';Assert-Paused $x 'host exit'
  $x=New-Case 'host-exit.json';Tick $x 1;[void](& $x.adapter.stop 'S-0001');$stoppedHost=@(& $x.adapter.emit_observation $x.run);Assert-True ($stoppedHost.Count -eq 0) 'stopped fake session emits no host observation'
  $x=New-Case 'probe-illegal-jump.json';Tick $x 2;Assert-True ($x.run.state.nodes.A.pause_reason -eq 'illegal-terminal-transition' -and $x.run.state.nodes.A.terminal_state -eq 'running') 'illegal terminal jump rejected';Assert-True (@(Read-RelayEvents $x.run|Where-Object{$_.reason-like'transition-rejected:*'}).Count -eq 1) 'illegal transition event recorded';Assert-Paused $x 'illegal jump'
  $x=New-Case 'probe-running-forever.json';Tick $x 1;$r=Submit-RelayResultFile $x.run 'A' (Join-Path $PSScriptRoot 'fixtures/runner/results/result-A1-interrupted.json');Assert-True ($r.ok -and $x.run.state.nodes.A.pause_reason -eq 'worker-reported-interruption') 'worker interruption accepted and paused';Assert-Paused $x 'worker interruption'
  $x=New-Case 'probe-running-forever.json';Tick $x 1;$r=Submit-RelayResultFile $x.run 'A' (Join-Path $PSScriptRoot 'fixtures/runner/results/result-A1-quota.json');Assert-True (-not $r.ok -and $r.reason -eq 'reserved-target-form') 'quota final rejected reserved';Assert-True ($x.run.state.nodes.A.result_status -eq 'interrupted_unknown' -and $x.run.state.nodes.A.pause_reason -eq 'quota-fallback') 'quota fallback projected interruption';Assert-True (-not(Test-Path (Join-Path $x.run.paths.attempts 'A/1/result.json'))) 'quota final not committed';Assert-Paused $x 'quota fallback'
  $x=New-Case 'probe-running-forever.json';Tick $x 1;$r=Submit-RelayResultFile $x.run 'A' (Join-Path $PSScriptRoot 'fixtures/failures/result-halfwritten.json');Assert-True (-not$r.ok -and $x.run.state.nodes.A.task_state -eq 'active' -and $x.run.state.nodes.A.result_status -eq 'working') 'halfwritten result rejected without pause or advance'
  $x=New-Case 'blocked-stop-ignore-probe-errors.json';Tick $x 1;$r=Submit-RelayResultFile $x.run 'A' (Join-Path $PSScriptRoot 'fixtures/runner/results/result-A1-blocked.json');Tick $x 4
  Assert-True ($r.ok -and $x.run.state.nodes.A.scheduling -eq 'blocked') 'blocked final remains blocked after later probe errors'
  Assert-True ($x.run.state.nodes.A.task_state -eq 'active' -and $x.run.state.nodes.A.result_status -eq 'dependency_blocked') 'blocked final business projection is unchanged'
  Assert-True (@(Read-RelayEvents $x.run|Where-Object{$_.reason-eq'probe-lost'}).Count -eq 0) 'blocked final does not emit probe-lost'
  $replan=Submit-RelayProposal $x.run (RF 'plans/plan-v2-replan-B-before-A.json') 1;Assert-True ($replan.ok -and $x.run.state.nodes.A.scheduling -eq 'waiting') 'replan resets blocked A to waiting'
  Assert-True ('B' -cin @(Get-RelayReadyNodes $x.run)) 'B is ready before resumed A'
  $started=Start-RelayNodeAttempt $x.run 'B';[void](Invoke-RelayTick $x.run);Assert-True ($started.ok -and $x.run.state.nodes.B.scheduling -eq 'launched') 'B launches and probes after replan'
  $script:t=[DateTimeOffset]::Parse('2026-08-15T09:00:00Z');$depRoot=Join-Path ([IO.Path]::GetTempPath()) "relay-test-failures-$([guid]::NewGuid().ToString('N'))";$script:roots.Add($depRoot);$depAdapter=New-RelayFakeAdapter (RF 'adapter/probe-errors-3.json');$depRun=New-RelayRun $depRoot 'RUN-FAKE-DHR02-DEC' $depAdapter {$script:t};[void](Submit-RelayProposal $depRun (RF 'plans/plan-v1-decision-ABC.json') 0);[void](Start-RelayNodeAttempt $depRun 'A');Tick @{run=$depRun} 4
  Assert-True ($depRun.state.nodes.A.scheduling -eq 'paused' -and $depRun.state.nodes.C.scheduling -eq 'waiting' -and 'C' -cnotin @(Get-RelayReadyNodes $depRun)) 'paused dependency keeps C waiting and not ready'
  [void](Invoke-RelayTick $depRun);Assert-True ($depRun.state.nodes.C.scheduling -eq 'waiting' -and 'C' -cnotin @(Get-RelayReadyNodes $depRun)) 'later tick keeps dependent C waiting and not ready'
}finally{foreach($root in $script:roots){if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}}
Write-Host "ASSERTIONS $script:assertions";if($script:failed){Write-Host "SUITE FAIL ($script:failed)";exit 1};Write-Host 'SUITE PASS';exit 0
